Repository terraform-google-modules/terraform-google-kubernetes-engine, pull requests merged in 2019-06, with the labels that each got.

#156 fixes for integration tests
  Makefile
  examples/disable_client_cert/main.tf
  examples/disable_client_cert/outputs.tf
  test/fixtures/disable_client_cert/network.tf
  test/integration/disable_client_cert/controls/gcloud.rb
Labels: enhancement

#157 GKE 101: added guest_accelerator feature and tests
  .kitchen.yml
  autogen/cluster_regional.tf
  autogen/cluster_zonal.tf
  cluster_regional.tf
  cluster_zonal.tf
  examples/disable_client_cert/README.md
  examples/node_pool/main.tf
  helpers/generate_modules/generate_modules.py
  modules/private-cluster/cluster_regional.tf
  modules/private-cluster/cluster_zonal.tf
  test/integration/node_pool/controls/gcloud.rb
  test/integration/node_pool/controls/kubectl.rb
Labels: enhancement

#149 Add initial_node_count variable for scaling the default node pool
  README.md
  autogen/cluster_regional.tf
  autogen/cluster_zonal.tf
  autogen/variables.tf
  cluster_regional.tf
  cluster_zonal.tf
  modules/private-cluster/README.md
  modules/private-cluster/cluster_regional.tf
  modules/private-cluster/cluster_zonal.tf
  modules/private-cluster/variables.tf
  variables.tf
Labels: enhancement

#159 Add network_policy to google_container_cluster
  .kitchen.yml
  README.md
  autogen/cluster_regional.tf
  autogen/cluster_zonal.tf
  autogen/variables.tf
  cluster_regional.tf
  cluster_zonal.tf
  modules/private-cluster/README.md
  modules/private-cluster/cluster_regional.tf
  modules/private-cluster/cluster_zonal.tf
  modules/private-cluster/variables.tf
  test/ci_integration.sh
  variables.tf
Labels: bug, enhancement

#163 Add configuration flag for `pod_security_policy_config` #140
  .kitchen.yml
  CHANGELOG.md
  autogen/cluster_regional.tf
  autogen/cluster_zonal.tf
  autogen/main.tf
  autogen/outputs.tf
  autogen/variables.tf
  modules/private-cluster/README.md
  modules/private-cluster/cluster_regional.tf
  modules/private-cluster/cluster_zonal.tf
  modules/private-cluster/main.tf
  modules/private-cluster/outputs.tf
  modules/private-cluster/variables.tf
  outputs.tf
Labels: enhancement

#171 Fixing intermittent failing test case
  test/integration/node_pool/controls/kubectl.rb
Labels: bug

#176 Add Terraform and Kitchen state files to Dockerignore
  .dockerignore
Labels: enhancement

#165 Database encryption
  autogen/cluster_regional.tf
  autogen/cluster_zonal.tf
  autogen/variables.tf
  modules/beta-private-cluster/README.md
  modules/beta-private-cluster/cluster_regional.tf
  modules/beta-private-cluster/cluster_zonal.tf
  modules/beta-private-cluster/variables.tf
  modules/beta-public-cluster/README.md
  modules/beta-public-cluster/cluster_regional.tf
  modules/beta-public-cluster/cluster_zonal.tf
  modules/beta-public-cluster/variables.tf
Labels: enhancement

#193 Feature/cluster ipv4 cidr
  README.md
  autogen/README.md
  autogen/cluster_regional.tf
  autogen/cluster_zonal.tf
  autogen/main.tf
  autogen/outputs.tf
  autogen/variables.tf
  cluster_regional.tf
  cluster_zonal.tf
  main.tf
  modules/beta-private-cluster/README.md
  modules/beta-private-cluster/cluster_regional.tf
  modules/beta-private-cluster/cluster_zonal.tf
  modules/beta-private-cluster/main.tf
  modules/beta-private-cluster/variables.tf
  modules/beta-public-cluster/README.md
  modules/beta-public-cluster/cluster_regional.tf
  modules/beta-public-cluster/cluster_zonal.tf
  modules/beta-public-cluster/main.tf
  modules/beta-public-cluster/outputs.tf
  modules/beta-public-cluster/variables.tf
  modules/private-cluster/README.md
  modules/private-cluster/cluster_regional.tf
  modules/private-cluster/cluster_zonal.tf
  modules/private-cluster/main.tf
  modules/private-cluster/outputs.tf
  modules/private-cluster/variables.tf
  outputs.tf
  variables.tf
Labels: enhancement

#187 Creation of new variable configure_ip_masq controlling ip masq install
  README.md
  autogen/masq.tf
  autogen/variables.tf
  examples/stub_domains/main.tf
  masq.tf
  modules/beta-private-cluster/README.md
  modules/beta-private-cluster/masq.tf
  modules/beta-private-cluster/variables.tf
  modules/beta-public-cluster/README.md
  modules/beta-public-cluster/masq.tf
  modules/beta-public-cluster/variables.tf
  modules/private-cluster/README.md
  modules/private-cluster/masq.tf
  modules/private-cluster/variables.tf
  test/integration/stub_domains_private/controls/kubectl.rb
  variables.tf
Labels: enhancement

#188 Enabling two features in beta clusters
  autogen/cluster_regional.tf
  autogen/cluster_zonal.tf
  autogen/main.tf
  autogen/outputs.tf
  autogen/variables.tf
  cluster_zonal.tf
  modules/beta-private-cluster/cluster_zonal.tf
  modules/beta-private-cluster/main.tf
  modules/beta-private-cluster/outputs.tf
  modules/beta-private-cluster/variables.tf
  modules/beta-public-cluster/README.md
  modules/beta-public-cluster/cluster_regional.tf
  modules/beta-public-cluster/cluster_zonal.tf
  modules/beta-public-cluster/main.tf
  modules/beta-public-cluster/outputs.tf
  modules/beta-public-cluster/variables.tf
  modules/private-cluster/README.md
  modules/private-cluster/cluster_regional.tf
  modules/private-cluster/cluster_zonal.tf
  modules/private-cluster/main.tf
  modules/private-cluster/outputs.tf
  modules/private-cluster/variables.tf
Labels: enhancement

#200 Fixing failing test to use include instead of eq
  test/integration/node_pool/controls/kubectl.rb
Labels: bug

#194 Fixed doc generator
  README.md
  autogen/README.md
  examples/deploy_service/README.md
  examples/disable_client_cert/README.md
  examples/node_pool/README.md
  examples/shared_vpc/README.md
  examples/simple_regional/README.md
  examples/simple_regional_private/README.md
  examples/simple_zonal/README.md
  examples/simple_zonal_private/README.md
  examples/stub_domains/README.md
  examples/stub_domains_private/README.md
  helpers/combine_docfiles.py
  modules/private-cluster/README.md
  modules/private-cluster/variables.tf
  test/make.sh
  variables.tf
Labels: enhancement

#198 Updating google providers to 2.9
  README.md
  autogen/README.md
  examples/deploy_service/main.tf
  examples/disable_client_cert/main.tf
  examples/shared_vpc/main.tf
  examples/simple_regional/main.tf
  examples/simple_regional_private/main.tf
  examples/simple_zonal/main.tf
  examples/simple_zonal_private/main.tf
  examples/stub_domains/main.tf
  modules/beta-private-cluster/README.md
  modules/beta-public-cluster/README.md
  modules/private-cluster/README.md
Labels: enhancement
