Repository terraform-google-modules/terraform-google-kubernetes-engine, pull requests merged in 2019-07, with the labels that each got.

#205 Patch breaking changes
  autogen/cluster_regional.tf
  autogen/cluster_zonal.tf
  autogen/main.tf
  cluster_regional.tf
  cluster_zonal.tf
  main.tf
  modules/beta-private-cluster/cluster_regional.tf
  modules/beta-private-cluster/cluster_zonal.tf
  modules/beta-private-cluster/main.tf
  modules/beta-public-cluster/cluster_regional.tf
  modules/beta-public-cluster/cluster_zonal.tf
  modules/beta-public-cluster/main.tf
  modules/private-cluster/cluster_regional.tf
  modules/private-cluster/cluster_zonal.tf
  modules/private-cluster/main.tf
Labels: bug

#203 Restrict node access to cluster metadata service
  .kitchen.yml
  autogen/cluster_regional.tf
  autogen/cluster_zonal.tf
  autogen/main.tf
  autogen/variables.tf
  examples/workload_metadata_config/README.md
  examples/workload_metadata_config/main.tf
  examples/workload_metadata_config/outputs.tf
  examples/workload_metadata_config/test_outputs.tf
  examples/workload_metadata_config/variables.tf
  modules/beta-private-cluster/README.md
  modules/beta-private-cluster/cluster_regional.tf
  modules/beta-private-cluster/cluster_zonal.tf
  modules/beta-private-cluster/main.tf
  modules/beta-private-cluster/variables.tf
  modules/beta-public-cluster/README.md
  modules/beta-public-cluster/cluster_regional.tf
  modules/beta-public-cluster/cluster_zonal.tf
  modules/beta-public-cluster/main.tf
  modules/beta-public-cluster/variables.tf
  test/ci/workload-metadata-config.yml
  test/fixtures/workload_metadata_config/example.tf
  test/fixtures/workload_metadata_config/network.tf
  test/fixtures/workload_metadata_config/outputs.tf
  test/fixtures/workload_metadata_config/terraform.tfvars
  test/fixtures/workload_metadata_config/variables.tf
  test/integration/workload_metadata_config/controls/gcloud.rb
  test/integration/workload_metadata_config/inspec.yml
Labels: enhancement

#201 README updates
  README.md
  autogen/README.md
  modules/beta-private-cluster/README.md
  modules/beta-public-cluster/README.md
  modules/private-cluster/README.md
Labels: bug, enhancement
